#!/usr/bin/zsh
# flags alias \
alias \
  pars="paru -Syu --skipreview --needed" \
  pad="paru --devel --needed -Syu" \
  par="paru -S --skipreview --needed" \
  prs='paru --color always -Sl | sed -e "s: :/:; s/ unknown-version//; /installed/d" | fzf --multi --ansi --preview "paru -Si {1}" | xargs -ro paru -S --skipreview --needed' \
  p="sudo pacman -S --needed" \
  sn="sync" \
  so="sudo " \
  rf="sudo reflector --country Singapore, --latest 20 --sort age --protocol https --save /etc/pacman.d/mirrorlist" \
  si="du -shc * | sort -rh | less" \
	s="setsid -f st" \
	pacman="sudo pacman" \
	pac="pacman -Syu --needed" \
	systemctl="sudo systemctl" \
	sv="sudo nvim" \
	ssp="sync && sudo systemctl suspend" \
  config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME' \
  cu='config add ~/.local/bin/* ~/.nvimrc ~/.zshrc && config commit -a -m "new" && config push' \
  c='cd "$( sudo find / -type d | fzf )"' \
  cpl='config --reset hard && config pull'

# cd
alias \
	vs="cd ~/local/st && nvim config.h" \
	sr="cd ~/.local/bin" \
	dw="cd ~/local/dwm" \
  vd="cd ~/local/dwm && nvim config.h" \
  vs="cd ~/local/st && nvim config.h" \
  vdm="cd ~/local/dmenu && nvim config.h" \
  vdw="cd ~/local/dwmblocks && nvim blocks.h" \
	vsl="cd ~/local/slstatus && nvim config.h" \
	dof="cd ~/dotfiles && sy" \
  dt="cd /tmp" \
  co="cd ~/.config && ls" \
	sk="cd ~/shared-files"\
  vi="cd ~/Downloads/torrent && lfub" \
  ani="cd ~/Downloads/anime && lfub" \
  a="cd aliases" \
  cl="cd ~/local" \
  cw="cd ~/.local/share/wallpaper" \
  walauto="wal -a .75 -i ~/.local/share/wallpaper/bg.png -q" \
  vst="cd ~/.local/bin/statusbar"

# nvim
alias \
	xi="nvim ~/.xinitrc" \
	vp="nvim ~/.config/picom.conf" \
	vz="nvim ~/.zshrc" \
  vvim="nvim ~/.config/nvim/init.vim" \
	vv="nvim config.h" \
  vb="nvim blocks.h" \
	zs="nvim ~/.zshrc" \
	va="nvim ~/.local/share/alias/aliases" \
  vap="nvim ~/.local/share/alias/aliases-laptop" \
  al="nvim ~/aliases/scripts" \
  vas="nvim ~/.local/share/alias/sites" \
  vac="nvim ~/.local/share/alias/clipboard" \
  th="nvim ~/.local/share/theme/colors.h"

# shorten 
alias \
	z="zathura" \
	g="git" \
  zr="zaread" \
	br="chromium" \
	vm="sudo systemctl restart vmware-networks.service && vmware" \
	pv="pavucontrol" \
  v="nvim" \
	i="sxiv" \
	tu="tremc" \
	n="watch -n1 nvidia-smi" \
	tor="transmission-remote" \
	pm="pulsemixer" \
  ht="htop" \
  sme="sudo make install" \
	ki="killall" \
  l="lfcd" \
  lf="lfub" \
  ksl="killall slstatus ; slstatus &"

# github
alias \
	fush="git commit -a -m "newest" && git push origin" \
	gps="git commit -a && git push origin" \
	fp="git fetch --all && git reset --hard origin/master" \
  gr="git reset --hard HEAD && git pull" \
  gs="git status" \
	gpl="git pull"

# verbosity
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  mkd="mkdir -pv" \
  yt="yt-dlp --embed-metadata -i" \
  yta="yt -x -f bestaudio/bestub"

# colorize 
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"

alias \
  fl="cd ~/dotfiles && gpl && ~/dotfiles/for-laptop" \
  fn="~/dotfiles/for-pc && cd ~/dotfiles && git add . && fush" \
  sen="watch -n1 sensors && k nvidia-smi" \
  te='watch -n1 "nvidia-smi && sensors"' \
  slt="killall slstatus ; sleep 1 && slstatus &" \
  dwt="sme && killall dwmblocks ; sleep 0.1 && dwmblocks &" \
  umi="/usr/local/Umineko/onscripter-ru" \
  cwal="nvim ~/.cache/wal/colors-wal-st.h"

# # before poweroff
# alias \
#   poweroff="before-poweroff && poweroff" \
#   reboot="before-poweroff && reboot"
